# Created by use_targets()

# Load packages required to define the pipeline:
library(targets)
library(tarchetypes)

# Set target options:
tar_option_set(
  packages = c("tidyverse"),
  error = "continue"
)

# Run the R scripts with custom functions:
tar_source(files = c(
  "3_harmonize.R",
  "create_bookdown.R"))

# The list of targets/steps
config_targets <- list(
  
  # Targets imported from the previous pipeline: ----------------------------
  
  # The local directory where the first {targets} pipeline is located (i.e.,
  # the pipeline that runs the download step)
  tar_target(name = p0_AquaMatch_download_WQP_directory,
             command = "../AquaMatch_download_WQP/"),
  
  # Confirm the presence of the {targets} WQP download pipeline
  tar_target(name = p0_AquaMatch_download_WQP_confirm,
             command = if(!dir.exists(p0_AquaMatch_download_WQP_directory)) {
               # Throw an error if the pipeline does not exist
               stop("The WQP download pipeline is not at the specified location.")
             },
             # The presence of the first pipeline is necessary for this one to run
             error = "stop"),
  
  # Retrieve links to data from Google Drive
  
  # Should the pipeline use a version of the dataset marked as "stable" or
  # use the dynamic outputs of the download pipeline? "Stable" means that re-running
  # the upstream download steps won't affect the input dataset in this pipeline
  # because the link to an existing ("stable") version dataset on Google Drive
  # is manually coded into the download pipeline. If TRUE, then use stable version.
  # If FALSE, then use the most recent results dynamically generated by the 
  # download pipeline. FALSE will only function if you have run the "AquaSat_download_WQP" targets pipeline to create a new download
  tar_target(data_version_stable,
             TRUE),
  
  # Location of parameter CharacteristicNames link
  # Toggle link to use based on which dataset version (stable or not)
  tar_file_read(p1_wqp_params_link,
                command = {
                  if(data_version_stable){
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "1_inventory/out/p1_wqp_params_out_link_stable.csv")
                  } else {
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "1_inventory/out/p1_wqp_params_out_link.csv")
                  }
                },
                cue = tar_cue("always"),
                read = read_csv(file = !!.x)),
  
  # Location of inventory/download area of interest link
  tar_file_read(p1_wqp_inventory_aoi_link,
                command = {
                  if(data_version_stable){
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "1_inventory/out/p1_wqp_inventory_aoi_out_link_stable.csv")
                  } else {
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "1_inventory/out/p1_wqp_inventory_aoi_out_link.csv")
                  }
                },
                read = read_csv(file = !!.x)),
  
  # Location of spatial grid link
  tar_file_read(p1_global_grid_link,
                command = {
                  if(data_version_stable){
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "1_inventory/out/p1_global_grid_out_link_stable.csv")
                  } else {
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "1_inventory/out/p1_global_grid_out_link.csv")
                  }
                },
                read = read_csv(file = !!.x)),
  
  # Location of CharacteristicName - parameter name crosswalk link
  tar_file_read(p1_char_names_crosswalk_link,
                command = {
                  if(data_version_stable){
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "1_inventory/out/p1_char_names_crosswalk_out_link_stable.csv")
                  } else {
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "1_inventory/out/p1_char_names_crosswalk_out_link.csv")
                  }
                },
                read = read_csv(file = !!.x)),
  
  # Location of inventory site counts link
  tar_file_read(p2_site_counts_link,
                command = {
                  if(data_version_stable){
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "2_download/out/p2_site_counts_out_link_stable.csv")
                  } else {
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "2_download/out/p2_site_counts_out_link.csv")
                  }
                },
                read = read_csv(file = !!.x)),
  
  # Location of link to downloaded WQP data from within area of interest
  tar_file_read(p2_wqp_data_aoi_out_links,
                command = {
                  if(data_version_stable){
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "2_download/out/p2_wqp_data_aoi_out_links_stable.csv")
                  } else {
                    paste0(p0_AquaMatch_download_WQP_directory,
                           "2_download/out/p2_wqp_data_aoi_out_links.csv")
                  }
                },
                read = read_csv(file = !!.x)),
  
  # Download data sets of interest:
  tar_target(p1_wqp_params,
             retrieve_data(link_table = p1_wqp_params_link,
                           folder_pattern = "1_inventory/out/"),
             packages = c("tidyverse", "googledrive")),
  
  tar_target(p1_wqp_inventory_aoi,
             retrieve_data(link_table = p1_wqp_inventory_aoi_link,
                           folder_pattern = "1_inventory/out/"),
             packages = c("tidyverse", "googledrive")),
  
  tar_target(p1_global_grid,
             retrieve_data(link_table = p1_global_grid_link,
                           folder_pattern = "1_inventory/out/"),
             packages = c("tidyverse", "googledrive")),
  
  tar_target(p1_char_names_crosswalk,
             retrieve_data(link_table = p1_char_names_crosswalk_link,
                           folder_pattern = "1_inventory/out/"),
             packages = c("tidyverse", "googledrive")),
  
  tar_target(p2_site_counts,
             retrieve_data(link_table = p2_site_counts_link,
                           folder_pattern = "2_download/out/"),
             packages = c("tidyverse", "googledrive")),
  
  tar_target(p2_wqp_data_aoi_chl,
             retrieve_param_data(link_table = p2_wqp_data_aoi_out_links,
                                 parameter_string = "chlorophyll"),
             format = "feather",
             packages = c("tidyverse", "googledrive", "feather")),
  
  tar_target(p2_wqp_data_aoi_doc,
             retrieve_param_data(link_table = p2_wqp_data_aoi_out_links,
                                 parameter_string = "doc"),
             format = "feather",
             packages = c("tidyverse", "googledrive", "feather"))
  
)


# Full targets list
c(config_targets,
  p3_targets_list,
  bookdown_targets_list)