---
output:
  github_document:
    html_preview: false
always_allow_html: true
---

# Technical details 

AquaSat v2 uses the {targets} workflow management R package to reimagine the [original AquaSat codebase](https://github.com/GlobalHydrologyLab/AquaSat) (Landau, 2021). The framework for this workflow is based on code adapted from [this USGS pipeline](https://github.com/USGS-R/ds-pipelines-targets-example-wqp) and has been further developed by members of the [ROSSyndicate](https://github.com/rossyndicate).

Technical details on {targets} workflows are available in the  [{targets} User Manual](https://books.ropensci.org/targets/). {targets} workflows are built upon lists of "targets", which can be thought of as analytical steps written out in code. This workflow uses a targets list spread across multiple scripts in an effort to facilitate organization of the code. `_targets.R` serves as a main list of targets and references the other lists of targets, which are defined inside `3_harmonize.R` and `create_bookdown.R`. Note that the downloading and harmonizing scripts for WQP data are spread across two GitHub repositories: [AquaMatch_download_WQP](https://github.com/AquaSat/AquaMatch_download_WQP) and [AquaMatch_harmonize_WQP](https://github.com/AquaSat/AquaMatch_harmonize_WQP), respectively.