---
output:
  github_document:
  html_preview: false
always_allow_html: true
---

# References

Davies-Colley, R. J., W. N. Vant, and D. G. Smith. 1993. Colour and Clarity of Natural Waters: Science and Management of Optical Water Quality, Ellis Horwood.

DeCicco, L. and others. 2024. dataRetrieval: R packages for discovering and retrieving water data available from U.S. federal hydrologic web services. doi:10.5066/P9X4L3GE

Gieskes, W. W. C., C. Veth, A. Woehrmann, and M. Graefe. 1987. Secchi disc visibility world record shattered. Eos, Transactions American Geophysical Union 68: 123–123. doi:10.1029/EO068i009p00123-01

Landau, W. M. 2021. The targets R package: a dynamic Make-like function-oriented pipeline toolkit for reproducibility and high-performance computing. Journal of Open Source Software 6: 2959.

Larson, D. W. 1972. Temperature, transparency, and phytoplankton productivity in Crater Lake, Oregon. Limnology and Oceanography 17: 410–417. doi:10.4319/lo.1972.17.3.0410

National Water Quality Monitoring Council, United States Geological Survey (USGS), and Environmental Protection Agency (EPA). 2021. Water Quality Portal.doi:https://doi.org/10.5066/P9QRKUVJ

North American Lake Management Society (NALMS). Secchi Records. https://www.nalms.org/secchidipin/monitoring-methods/the-secchi-disk/secchi-records/. Accessed 2024-09-17.

Ross, M. R. V., S. N. Topp, A. P. Appling, X. Yang, C. Kuhn, D. Butman, M. Simard, and T. M. Pavelsky. 2019. AquaSat: A Data Set to Enable Remote Sensing of Water Quality for Inland Waters. Water Resources Research 55: 10012–10025. doi:10.1029/2019WR024883

Teucher, A. 2023. lutz: Look Up Time Zones of Point Coordinates. R package version 0.3.2, https://CRAN.R-project.org/package=lutz.

Wetzel, R. G. 2011. Limnology: lake and river ecosystems, 3. ed. San Diego: Academic Press.
