# A function that plots bar charts of record counts by year, month, and day of week

plot_time_charts <- function(dataset, parameter,
                             custom_width = 6, custom_height = 4){
  
  # Grab year data and plot record counts
  year_plot <- dataset %>%
    select(harmonized_local_time, tier) %>%
    mutate(year = year(harmonized_local_time),
           tier = factor(x = tier, levels = c(2, 1, 0), ordered = TRUE)) %>%
    count(year, tier) %>%
    ggplot() +
    geom_bar(aes(x = year, y = n, fill = tier),
             color = "gray20", stat = "identity") +
    ylab("Record count") +
    xlab("Activity year") +
    ggtitle(paste0(toupper(parameter), " record distribution by year & tier")) +
    scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) +
    scale_fill_viridis_d("Tier") +
    theme_bw()
  
  # Export with autogenerated filename
  ggsave(filename = paste0("3_harmonize/out/",
                           parameter, "_",
                           "year_tier_chart.png"),
         plot = year_plot, units = "in", device = "png",
         width = custom_width, height = custom_height)
  
  # Day of week
  day_plot <- dataset %>%
    select(harmonized_local_time, tier) %>%
    mutate(weekday = wday(harmonized_local_time, label = TRUE),
           tier = factor(x = tier, levels = c(2, 1, 0), ordered = TRUE)) %>%
    count(weekday, tier) %>%
    ggplot() +
    geom_bar(aes(x = weekday, y = n, fill = tier),
             color = "gray20", stat = "identity") +
    ylab("Record count") +
    xlab("Activity day") +
    ggtitle(paste0(toupper(parameter), " record distribution by day of week & tier")) +
    scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) +
    scale_fill_viridis_d("Tier") +
    theme_bw()
  
  ggsave(filename = paste0("3_harmonize/out/",
                           parameter, "_",
                           "wday_tier_chart.png"),
         plot = day_plot, units = "in", device = "png",
         width = custom_width, height = custom_height)
  
  # Month
  month_plot <- dataset %>%
    select(harmonized_local_time, tier) %>%
    mutate(month = month(harmonized_local_time, label = TRUE),
           tier = factor(x = tier, levels = c(2, 1, 0), ordered = TRUE)) %>%
    count(month, tier) %>%
    ggplot() +
    geom_bar(aes(x = month, y = n, fill = tier),
             color = "gray20", stat = "identity") +
    ylab("Record count") +
    xlab("Activity month") +
    ggtitle(paste0(toupper(parameter), " record distribution by month & tier")) +
    scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) +
    scale_fill_viridis_d("Tier") +
    theme_bw()
  
  ggsave(filename = paste0("3_harmonize/out/",
                           parameter, "_",
                           "month_tier_chart.png"),
         plot = month_plot, units = "in", device = "png",
         width = custom_width, height = custom_height)
  
}
