# A function that plots bar charts of record counts by year, month, and day of week

#' @title Create bar charts of record counts by data tier
#' 
#' @description
#' A function that creates hex maps of record counts for each tier of a selected
#' parameter's harmonized dataset. The maps are created as a single paneled ggplot
#' object and then exported as a single PNG file.
#' 
#' @param dataset A data frame of the harmonized parameter's dataset containing
#' the columns `tier`, `MonitoringLocationIdentifier`, `lat`, `lon`, and `datum`.
#' Intended to be the version of the dataset with simultaneous observations removed. 
#' @param parameter A string containing the abbreviated name of the parameter:
#' e.g., "chla", "doc", etc.
#' @param map_crs The epsg code that should be used when creating the maps.
#' @param custom_width The desired output PNG width in inches.
#' @param custom_height The desired output PNG height in inches.

plot_time_charts <- function(dataset, parameter,
                             custom_width = 6, custom_height = 4){
  
  tier_levels <- sort(unique(dataset$tier))
  
  # Grab year data and plot record counts
  year_plot <- dataset %>%
    select(harmonized_local_time, tier) %>%
    mutate(year = year(harmonized_local_time),
           tier = factor(x = tier, levels = tier_levels, ordered = TRUE)) %>%
    count(year, tier) %>%
    ggplot() +
    geom_bar(aes(x = year, y = n, fill = tier),
             color = "gray20", stat = "identity") +
    ylab("Record count") +
    xlab("Activity year") +
    ggtitle(paste0(toupper(parameter), " record distribution by year & tier")) +
    scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) +
    scale_fill_viridis_d("Tier", direction = -1) +
    theme_bw()
  
  # Export with autogenerated filename
  ggsave(filename = paste0("3_harmonize/out/",
                           parameter, "_",
                           "year_tier_chart.png"),
         plot = year_plot, units = "in", device = "png",
         width = custom_width, height = custom_height)
  
  # Day of week
  day_plot <- dataset %>%
    select(harmonized_local_time, tier) %>%
    mutate(weekday = wday(harmonized_local_time, label = TRUE),
           tier = factor(x = tier, levels = tier_levels, ordered = TRUE)) %>%
    count(weekday, tier) %>%
    ggplot() +
    geom_bar(aes(x = weekday, y = n, fill = tier),
             color = "gray20", stat = "identity") +
    ylab("Record count") +
    xlab("Activity day") +
    ggtitle(paste0(toupper(parameter), " record distribution by day of week & tier")) +
    scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) +
    scale_fill_viridis_d("Tier", direction = -1) +
    theme_bw()
  
  ggsave(filename = paste0("3_harmonize/out/",
                           parameter, "_",
                           "wday_tier_chart.png"),
         plot = day_plot, units = "in", device = "png",
         width = custom_width, height = custom_height)
  
  # Month
  month_plot <- dataset %>%
    select(harmonized_local_time, tier) %>%
    mutate(month = month(harmonized_local_time, label = TRUE),
           tier = factor(x = tier, levels = tier_levels, ordered = TRUE)) %>%
    count(month, tier) %>%
    ggplot() +
    geom_bar(aes(x = month, y = n, fill = tier),
             color = "gray20", stat = "identity") +
    ylab("Record count") +
    xlab("Activity month") +
    ggtitle(paste0(toupper(parameter), " record distribution by month & tier")) +
    scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) +
    scale_fill_viridis_d("Tier", direction = -1) +
    theme_bw()
  
  ggsave(filename = paste0("3_harmonize/out/",
                           parameter, "_",
                           "month_tier_chart.png"),
         plot = month_plot, units = "in", device = "png",
         width = custom_width, height = custom_height)
  
}
