---
title: "True_Color"
author: "Daniel Dominguez"
format: 
  html:
    code-fold: true
    code-summary: "Show the code"
#page-layout: full
fig-width: 15
execute:
  echo: true
  warning: false
  error: false
  message: false
---

```{r, echo = FALSE}
tar_load(harmonized_true_color)
```

```{r, echo = FALSE}
harmonized_true_color$parameter_barplot
```

```{r, echo = FALSE}
harmonized_true_color$parameter_count %>%
  kable("html") %>% 
  kable_styling("striped", full_width = F)
```

```{r, echo = FALSE}
harmonized_true_color$true_color_unique_methods %>%
  kable("html") %>% 
  kable_styling("striped", full_width = F)
```

```{r, echo = FALSE}
harmonized_true_color$true_color_sample_methods %>%
  kable("html") %>% 
  kable_styling("striped", full_width = F)
```

```{r echo = FALSE}
harmonized_true_color$apparent_methods_plot
```

```{r echo = FALSE}
harmonized_true_color$color_methods_plot
```

```{r echo = FALSE}
harmonized_true_color$true_color_methods_plot
```

```{r}
harmonized_true_color$class_param_plot
```
