---
title: "TSS"
author: ""
format: 
  html:
    code-fold: true
    code-summary: "Show the code"
#page-layout: full
fig-width: 15
execute:
  echo: true
  warning: false
  error: false
  message: false
---

```{r echo=FALSE}
raw_tss <- input_var$raw_tss
p_codes <- input_var$p_codes
```

## Aggregating

```{r}
raw_tss <- raw_tss %>%
  dplyr::select(date = ActivityStartDate,
                parameter = CharacteristicName,
                units = ResultMeasure.MeasureUnitCode,
                SiteID = MonitoringLocationIdentifier,
                org = OrganizationFormalName,
                org_id = OrganizationIdentifier,
                time = ActivityStartTime.Time,
                value = ResultMeasureValue,
                sample_method = SampleCollectionMethod.MethodName,
                analytical_method = ResultAnalyticalMethod.MethodName,
                particle_size = ResultParticleSizeBasisText,
                date_time = ActivityStartDateTime,
                media = ActivityMediaName,
                sample_depth = ActivityDepthHeightMeasure.MeasureValue,
                sample_depth_unit = ActivityDepthHeightMeasure.MeasureUnitCode,
                fraction = ResultSampleFractionText,
                status = ResultStatusIdentifier) %>%
  # Remove trailing white space in labels (Is this still necessary?)
  mutate(units = trimws(units)) %>%
  #Keep only samples that are water samples
  filter(media == "Water")
```

```{r echo=FALSE} 
unit_kable(raw_tss)
```

```{r echo=FALSE}
analytical_kable(raw_tss)
```

```{r tss analytical method filtering}
# There are a lot of parameter codes so we are just going to use a grepl command
# with key words that definitely disqualify the sample

nonsensical_tss_methods <- raw_tss %>%
  filter(grepl(pattern = "Oxygen|Nitrogen|Ammonia|Metals|E. coli|Carbon|Anion|Cation|Phosphorus|Silica|PH|HARDNESS|Nutrient|Turbidity|Temperature|Nitrate|Conductance|Alkalinity|Chlorophyll",
               x = analytical_method,
               ignore.case = T))

tss_filtered <- raw_tss %>%
  filter(!analytical_method %in% nonsensical_tss_methods$analytical_method)

print(
  paste("We dropped",
        round(nrow(nonsensical_tss_methods) / nrow(raw_tss) * 100,2),
        '% of samples, because the method used did not make sense. These methods are:')
)

# Nice function for printing long vectors horizontally separated by dash
p(unique(nonsensical_tss_methods$analytical_method),
  wrap = "",
  sep = " - ")
```

### TSS depth of sampling

```{r depth breakdown}
# Define a depth lookup table to convert all depth data to meters. 
depth_lookup <- tibble(sample_depth_unit = c("cm", "feet", "ft", "in", "m",
                                             "meters", "None"),
                       depth_conversion = c(1 / 100, .3048, .3048, 0.0254,
                                            1, 1, NA)) 

# Join depth lookup table to tss data
tss_depth <- inner_join(x = raw_tss,
                        y = depth_lookup,
                        by = c("sample_depth_unit")) %>%
  # Some depth measurements have negative values (assume that is just preference)
  # I also added .01 meters because many samlples have depth of zero assuming
  # they were taken directly at the surface
  mutate(harmonized_depth = abs(sample_depth * depth_conversion) + .01)

# We lose lots of data by keeping only data with depth measurements
print(paste("If we only kept samples that had depth information we would lose",
            round((nrow(raw_tss) - nrow(tss_depth)) / nrow(raw_tss) * 100, 1),
            "% of samples"))

ggplot(tss_depth, aes(x = harmonized_depth)) + 
  geom_histogram(bins = 100) + 
  scale_x_log10(limits = c(0.01, 10^3), breaks = c(.1, 1, 10, 100)) 
```

## TSS Unit Harmonization

### TSS disharmony

#### TSS particle size fractionation

```{r, fig.width=5}
# Select only units for %
tss_perc <- raw_tss %>%
  filter(units == "%") 

# Look at the breakdown of particle sizes
tss_perc %>%
  group_by(particle_size) %>%
  summarize(count = n()) %>%
  kable(.,
        "html",
        caption = "All particle size fractions and their count") %>%
  kable_styling() %>%
  scroll_box(width = "600px", height = "400px")

# Keep only the sand fraction data (~50% of the data)
sand.harmonized  <- tss_perc %>%
  filter(particle_size %in%  c("< 0.0625 mm","sands")) %>%
  mutate(conversion = NA,
         harmonized_parameter = "p.sand",
         harmonized_value = value,
         harmonized_unit = "%")
```

#### TSS dropping bad units

```{r}
# Make a tss lookup table
tss_lookup <- tibble(units = c("mg/l", "g/l", "ug/l", "ppm"),
                     conversion = c(1, 1000, 1 / 1000, 1))


unit_disharmony(raw_tss, tss_lookup)



```

### TSS harmony in mg/l

```{r tss harmony}
# Join to the lookup table and harmonize units

tss_tis_harmonized <- raw_tss %>%
  inner_join(tss_lookup, by = "units") %>%
  mutate(harmonized_parameter = "tss",
         harmonized_value = value * conversion,
         harmonized_unit = "mg/l") %>%
  # Change harmonized parameter to tis for parameter "fixed suspended solids"
  mutate(harmonized_parameter = ifelse(parameter == "Fixed suspended solids", "tis", harmonized_parameter))

rm(tss, tss_depth, tss_filtered, tss_lookup, tss_p, nonsensical_tss_methods, depth_lookup)
gc()
```

## TSS SSC empirical check
```{r}
names(tss_tis_harmonized)

ssc_tss <- tss_tis_harmonized %>%
  filter(parameter %in% c("Total suspended solids",
                          "Suspended Sediment Concentration (SSC)")) %>%
  select(date, date_time, SiteID, parameter, harmonized_value) %>%
  distinct(date_time, SiteID, .keep_all = T) %>%
  spread(key = parameter, value = harmonized_value) %>% 
  rename(tss = `Total suspended solids`,
         ssc = `Suspended Sediment Concentration (SSC)`) 

ssc_tss %>%
  filter(!is.na(ssc)) %>%
  summary(.)
```






```{r echo=FALSE}
# NULL until script gets to the point of having output
return_value <- NULL
```











